import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { SiteShell } from "@/components/site-shell";
import { categories } from "@/lib/catalog-data";

export const Route = createFileRoute("/aromas")({ head: () => ({ meta: [
  { title: "Familias aromáticas — BEKOKO" }, { name: "description", content: "Descubre las familias y formatos aromáticos de BEKOKO." },
  { property: "og:title", content: "Familias aromáticas — BEKOKO" }, { property: "og:description", content: "Descubre las familias y formatos aromáticos de BEKOKO." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AromasPage });

function AromasPage() { return <SiteShell><header className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-24"><div className="flex items-center gap-3"><span className="h-1.5 w-12 bg-magenta"/><p className="text-xs font-bold uppercase text-magenta">Encuentra tu ritual</p></div><div className="mt-5 grid gap-7 lg:grid-cols-[1fr_.45fr] lg:items-end"><h1 className="font-display text-6xl leading-none sm:text-8xl">Aromas para cada espacio.</h1><p className="border-l-4 border-sun pl-5 leading-7 text-muted-foreground">Seis maneras de convertir un gesto cotidiano en una atmósfera personal.</p></div></header><section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{categories.map((category,index)=><Link key={category.name} to="/catalogo" className={`group ${index===1||index===4?"lg:translate-y-10":""}`}><div className="relative aspect-[4/5] overflow-hidden bg-muted"><img src={category.image} alt={category.name} width={912} height={1104} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/><span className={`absolute left-0 top-0 px-4 py-3 text-xs font-black uppercase ${category.accent==="magenta"?"bg-magenta text-on-color":category.accent==="sun"?"bg-sun text-ink":"bg-cyan text-ink"}`}>0{index+1}</span></div><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-b-2 border-border py-5 transition-colors group-hover:border-magenta"><div className="min-w-0"><h2 className="font-display text-3xl">{category.name}</h2><p className="mt-1 text-sm text-muted-foreground">{category.description}</p></div><ArrowRight className="transition-transform group-hover:translate-x-1"/></div></Link>)}</div></section><section className="mt-10 bg-cyan py-16 text-ink"><div className="mx-auto grid max-w-7xl gap-5 px-5 sm:px-8 lg:grid-cols-[1fr_auto] lg:items-center"><h2 className="max-w-3xl font-display text-5xl leading-none">¿No sabes cuál elegir? Empieza por aquello que quieres sentir.</h2><Link to="/contacto" className="inline-flex items-center gap-2 text-xs font-black uppercase">Conversemos <ArrowRight/></Link></div></section></SiteShell>; }
