import { createFileRoute } from "@tanstack/react-router";
import { Heart, Plus, Search, ShoppingBag, X, Tag } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { SiteShell } from "@/components/site-shell";
import { money, products, type Category, type Product } from "@/lib/catalog-data";
import bgCatalog from "@/assets/media/bg-catalog.mp4";

export const Route = createFileRoute("/catalogo")({
  head: () => ({ meta: [
    { title: "Catálogo de aromas — BEKOKO" }, { name: "description", content: "Explora velas, difusores, sprays, aceites, jabones y sets BEKOKO." },
    { property: "og:title", content: "Catálogo de aromas — BEKOKO" }, { property: "og:description", content: "Explora velas, difusores, sprays, aceites, jabones y sets BEKOKO." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: CatalogPage,
});

function CatalogPage() {
  const [filter, setFilter] = useState<"Todos" | Category>("Todos"); const [query, setQuery] = useState(""); const [sort, setSort] = useState("featured");
  const [favorites, setFavorites] = useState<number[]>([]); const [cartCount, setCartCount] = useState(0); const [selected, setSelected] = useState<Product | null>(null);
  const visible = useMemo(() => { const needle=query.toLocaleLowerCase("es"); const result=products.filter((p)=>(filter==="Todos"||p.category===filter)&&`${p.name} ${p.category} ${p.notes}`.toLocaleLowerCase("es").includes(needle)); return [...result].sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:sort==="az"?a.name.localeCompare(b.name):a.id-b.id); }, [filter,query,sort]);
  const toggleFavorite=(id:number)=>setFavorites((current)=>current.includes(id)?current.filter((item)=>item!==id):[...current,id]);
  return <SiteShell cartCount={cartCount} favoriteCount={favorites.length}>
    <header className="relative border-b border-border overflow-hidden"><video src={bgCatalog} autoPlay loop muted playsInline className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-black/70" /><div className="relative mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:py-12"><div className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-1 text-[9px] font-bold uppercase tracking-wider text-magenta"><span className="h-1.5 w-1.5 rounded-full bg-magenta" /> CATÁLOGO</div><h1 className="mt-4 font-sans text-4xl font-black text-white sm:text-5xl lg:text-6xl">Aromas para <span className="text-cyan">cada ambiente</span></h1><p className="mt-3 max-w-xl text-sm leading-6 text-white/80">Explorá nuestra selección de aromas. Buscá por nombre, filtrá por categoría y ordená como prefieras.</p><div className="mt-6 flex max-w-3xl flex-col gap-3 sm:flex-row"><label className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><span className="sr-only">Buscar productos</span><input suppressHydrationWarning value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar por nombre..." className="h-11 w-full rounded-full border-none bg-white pl-10 pr-4 text-sm text-black outline-none focus:ring-2 focus:ring-cyan"/></label><label><span className="sr-only">Ordenar productos</span><select suppressHydrationWarning value={sort} onChange={(e)=>setSort(e.target.value)} className="h-11 w-full rounded-full border-none bg-white px-4 text-sm text-black outline-none focus:ring-2 focus:ring-cyan sm:w-48"><option value="featured">Destacados</option><option value="low">Menor precio</option><option value="high">Mayor precio</option><option value="az">Nombre A-Z</option></select></label></div></div></header>
    <section className="catalog-gradient pb-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="border-b border-border py-5"><div className="flex gap-2 overflow-x-auto">{(["Todos","Velas","Difusores","Sprays","Aceites","Jabones","Sets"] as const).map((item)=><Button key={item} variant={filter===item?"default":"ghost"} size="sm" className="shrink-0 rounded-full" onClick={()=>setFilter(item)}>{item}</Button>)}</div></div><p className="mt-7 text-xs font-bold uppercase text-magenta">{visible.length} productos</p><motion.div layout className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4"><AnimatePresence mode="popLayout">{visible.map((product)=><motion.article layout initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.9 }} transition={{ duration: 0.25 }} key={product.id} className="group flex min-w-0 flex-col rounded-2xl bg-[#111111] p-2.5 shadow-lg"><div className="relative aspect-[4/3] w-full overflow-hidden rounded-xl bg-muted"><button className="h-full w-full" onClick={()=>setSelected(product)} aria-label={`Ver detalle de ${product.name}`}><img src={product.image} alt={product.name} width={912} height={1104} loading="lazy" className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/></button><span className="absolute left-2 top-2 flex items-center gap-1 rounded-full bg-black/60 px-2 py-1 text-[8px] font-bold uppercase text-white backdrop-blur-md"><Tag className="h-2.5 w-2.5" /> {product.category}</span><Button variant="ghost" size="icon" className="absolute right-2 top-2 h-7 w-7 rounded-full bg-black/40 text-white backdrop-blur-md hover:bg-black/60" onClick={()=>toggleFavorite(product.id)} aria-label="Añadir a favoritos"><Heart className={`h-3 w-3 ${favorites.includes(product.id)?"fill-magenta text-magenta":""}`}/></Button></div><div className="mt-3 flex flex-1 flex-col px-1"><button onClick={()=>setSelected(product)} className="text-left"><h2 className="font-sans text-sm font-bold text-white sm:text-base">{product.name}</h2></button><p className="mt-0.5 truncate text-[10px] text-white/50">{product.category} - {product.notes}</p><div className="mt-auto flex items-center justify-between gap-2 pt-3"><span className="text-lg font-black text-white">{money.format(product.price)}</span><Button size="icon" className="h-8 w-8 rounded-full bg-cyan text-white hover:bg-cyan/90" onClick={()=>setCartCount((count)=>count+1)} aria-label="Agregar al carrito"><ShoppingBag className="h-4 w-4"/></Button></div></div></motion.article>)}</AnimatePresence></motion.div>{!visible.length&&<div className="py-24 text-center"><p className="font-display text-3xl">No encontramos aromas con esa búsqueda.</p><Button variant="link" onClick={()=>{setQuery("");setFilter("Todos");}}>Ver todos</Button></div>}</div></section>
    {selected&&<div className="fixed inset-0 z-[70] grid place-items-center bg-foreground/45 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={`Detalle de ${selected.name}`} onClick={()=>setSelected(null)}><div className="relative grid max-h-[92vh] w-full max-w-4xl overflow-y-auto bg-background shadow-2xl md:grid-cols-2" onClick={(e)=>e.stopPropagation()}><Button variant="secondary" size="icon" className="absolute right-3 top-3 z-10" onClick={()=>setSelected(null)} aria-label="Cerrar"><X/></Button><img src={selected.image} alt={selected.name} className="aspect-[4/5] h-full w-full object-cover"/><div className="flex flex-col justify-center p-7 sm:p-10"><p className="text-xs font-bold uppercase text-magenta">{selected.category}</p><h2 className="mt-3 font-display text-4xl sm:text-5xl">{selected.name}</h2><p className="mt-4 text-sm text-cyan">{selected.notes}</p><p className="mt-6 leading-7 text-muted-foreground">{selected.description}</p><p className="mt-7 text-xl font-bold">{money.format(selected.price)}</p><div className="mt-7 flex gap-3"><Button size="lg" className="flex-1" onClick={()=>setCartCount((count)=>count+1)}><ShoppingBag/>Agregar al carrito</Button><Button size="lg" variant="outline" onClick={()=>toggleFavorite(selected.id)} aria-label="Favorito"><Heart className={favorites.includes(selected.id)?"fill-magenta text-magenta":""}/></Button></div></div></div></div>}
  </SiteShell>;
}
