import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Heart, Leaf, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteShell } from "@/components/site-shell";
import editorialAsset from "@/assets/bekoko-editorial.jpg.asset.json";
import heroAsset from "@/assets/bekoko-hero.jpg.asset.json";

export const Route = createFileRoute("/nosotros")({ head: () => ({ meta: [
  { title: "Nuestra historia — BEKOKO" }, { name: "description", content: "Conoce la mirada, los materiales y los rituales que dan forma a BEKOKO." },
  { property: "og:title", content: "Nuestra historia — BEKOKO" }, { property: "og:description", content: "Conoce la mirada, los materiales y los rituales que dan forma a BEKOKO." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AboutPage });

function AboutPage(){return <SiteShell><section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 lg:grid-cols-12 lg:items-center lg:py-24"><div className="lg:col-span-5"><div className="flex items-center gap-3"><span className="h-1.5 w-12 bg-magenta"/><p className="text-xs font-bold uppercase text-magenta">Nuestra esencia</p></div><h1 className="mt-6 font-display text-6xl leading-[.95] sm:text-8xl">Diseñamos pausas para la vida cotidiana.</h1><p className="mt-7 border-l-4 border-sun pl-6 text-lg leading-8 text-muted-foreground">BEKOKO nace de una idea simple: el hogar se recuerda también por cómo huele.</p></div><div className="relative lg:col-span-7"><div className="absolute -left-3 -top-3 h-full w-full border-2 border-cyan"/><img src={editorialAsset.url} alt="Botánicos y vela que inspiran la esencia de BEKOKO" width={912} height={1200} className="relative aspect-[4/3] w-full object-cover"/></div></section><section className="bg-secondary py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><p className="text-xs font-bold uppercase text-magenta">Lo que nos mueve</p><div><h2 className="font-display text-5xl leading-none sm:text-6xl">Objetos sensibles, fórmulas cuidadas y una mirada contemporánea.</h2><p className="mt-7 max-w-3xl leading-8 text-muted-foreground">Trabajamos cada colección como una edición: seleccionamos notas, texturas y formatos que puedan convivir con tu espacio sin imponerse. Buscamos una presencia honesta, alegre y profundamente personal.</p></div></div><div className="mt-14 grid gap-5 sm:grid-cols-3">{[{icon:Leaf,title:"Ingredientes conscientes",text:"Selecciones nobles y fórmulas pensadas con intención.",tone:"bg-cyan"},{icon:Sparkles,title:"Pequeñas partidas",text:"Atención artesanal en cada detalle y cada mezcla.",tone:"bg-sun"},{icon:Heart,title:"Diseño cercano",text:"Piezas que acompañan tu vida, no solo la decoran.",tone:"bg-magenta text-on-color"}].map(({icon:Icon,title,text,tone})=><article key={title} className={`${tone} p-7 sm:p-9`}><Icon/><h3 className="mt-10 font-display text-3xl">{title}</h3><p className="mt-3 text-sm leading-6 opacity-70">{text}</p></article>)}</div></div></section><section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:items-center"><img src={heroAsset.url} alt="Productos BEKOKO en un hogar contemporáneo" className="aspect-[4/3] w-full object-cover"/><div><p className="text-xs font-bold uppercase text-cyan">Tu hogar, tu ritmo</p><h2 className="mt-4 font-display text-5xl leading-none">El ritual comienza donde tú quieras.</h2><p className="mt-6 leading-8 text-muted-foreground">Una vela al cerrar el día, un spray antes de recibir visitas o unas gotas de aceite para recuperar el foco.</p><Button className="mt-8" asChild><Link to="/catalogo">Explorar colección <ArrowRight/></Link></Button></div></section></SiteShell>}
